branch-defaults:
  master:
    environment: website-prod
    group_suffix: null
global:
  application_name: website
  branch: master
  default_ec2_keyname: nicholeuf
  default_platform: node.js
  default_region: us-east-2
  profile: default
  repository: null
  sc: git
