branch-defaults:
  master:
    environment: website-prod
global:
  application_name: website
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-east-1
  profile: eb-cli
  sc: git
