branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: website
  branch: master
  default_ec2_keyname: nicholeuf
  default_platform: node.js
  default_region: us-east-1
  profile: null
  repository: website
  sc: git
