branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: website
  branch: null
  default_ec2_keyname: nicholeuf
  default_platform: node.js
  default_region: us-east-2
  profile: null
  repository: null
  sc: git
