# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: gradientco/node-elastic-beanstalk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: yarn install
      # run tests!
      - run: yarn test
      - run: npm run lint

      - deploy:
          name: Deploy to AWS EB
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apt-get -y -qq update
              apt-get -y -qq install python3.4-dev
              curl -O https://bootstrap.pypa.io/get-pip.py
              python3.4 get-pip.py --user
              pip install awsebcli
              eb deploy --timeout 20
            fi
